version: '3.8'

services:
  backend:
    build: ./backend
    container_name: webtruyen-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: webtruyen-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  admin:
    build: ./admin-frontend
    container_name: webtruyen-admin
    ports:
      - "3001:3001"
    env_file:
      - ./admin-frontend/.env
    depends_on:
      - backend

  reader:
    build: ./web-reader
    container_name: webtruyen-reader
    ports:
      - "3000:3000"
    env_file:
      - ./web-reader/.env
    depends_on:
      - backend

volumes:
  mongo_data:
