services:
  - name: backend
    type: web
    env: node
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: PORT
        value: 3000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false

  - name: admin-frontend
    type: static
    rootDir: admin-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://backend.onrender.com

  - name: web-reader
    type: web
    env: node
    rootDir: web-reader
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NEXT_PUBLIC_API_BASE_URL
        value: https://backend.onrender.com
      - key: NEXT_PUBLIC_GOOGLE_CLIENT_ID
        sync: false
