services:
  - name: mongodb
    type: pserv
    env: docker
    plan: free
    repo: https://github.com/render-examples/mongodb
    buildFilter:
      paths:
        - ignored/never-trigger
    envVars:
      - key: MONGO_INITDB_ROOT_USERNAME
        value: root
      - key: MONGO_INITDB_ROOT_PASSWORD
        value: password

  - name: backend
    type: web
    env: node
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - fromService:
          type: pserv
          name: mongodb
          envVarKey: MONGODB_URI
      - key: PORT
        value: 3000
      - key: JWT_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false

  - name: admin-frontend
    type: web
    env: static
    rootDir: admin-frontend
    buildCommand: npm install && npm run build
    startCommand: ""
    staticPublishPath: dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://backend.onrender.com

  - name: web-reader
    type: web
    env: node
    rootDir: web-reader
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NEXT_PUBLIC_API_BASE_URL
        value: https://backend.onrender.com
      - key: NEXT_PUBLIC_GOOGLE_CLIENT_ID
        sync: false
