version: '3.8'

services:
  api:
    build: .
    container_name: webtruyen-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mongo
    command: npm run start:prod

  mongo:
    image: mongo:6.0
    container_name: webtruyen-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
